#pragma once

#include "WeaponSubclasses.h"

extern const vector<Sword> SwordsList;
enum gameSwordsNames {
    RUSTY_IRON_SWORD,
    OLD_SHORT_SWORD,
    TRAVELER_S_SWORD,
    BROKEN_LONG_SWORD,
    WORN_OUT_SCIMITAR,
    SIMPLE_BRONZE_BLADE,
    BLUNT_TRAINING_SWORD,
    
    STEEL_LONG_SWORD,
    HUNTER_S_BLADE,
    GLADIATOR_S_SHORT_SWORD,
    ORCISH_CLEAVER,
    JAGGED_EDGE_SABER,
    SERRATED_SWORD,
    KNIGHT_S_IRON_SWORD,
    
    ELVEN_SILVER_SWORD,
    ENCHANTED_STEEL_SWORD,
    DARKWOOD_BLADE,
    DWARVEN_BATTLE_GLADIUS,
    SEARING_FLAME_SABER,
    MOONLIT_BLADE,
    SWORD_OF_THE_FALLEN,
    
    DRAGON_SLAYER,
    SWORD_OF_THE_PHOENIX,
    SHADOWFANG,
    THUNDERSTRIKE,
    STORMBRINGER,
    BLOOD_OATH,
    BLADE_OF_THE_ANCIENTS,
    
    BLADE_OF_ETERNITY,
    CELESTIAL_EDGE,
    FROST_REAVER,
    INFERNO_S_WRATH,
    WRAITH_BLADE,
    SOULRENDER,
    WRATH_OF_THE_GODS,
    
    EXCALIBUR,
    SWORD_OF_THE_FORGOTTEN_KING,
    SHADOW_OF_AETHERIUS,
    THE_FINAL_BREATH,
    ECLIPSE_BLADE,

    NUM_SWORDS
};


extern const vector<Axe> AxesList;
enum gameAxesNames {
    RUSTY_HATCHET,
    SPLINTERED_WOODCUTTER_S_AXE,
    BASIC_WAR_AXE,
    CHIPPED_IRON_AXE,
    DULL_LUMBERJACK_S_AXE,

    STEEL_BATTLE_AXE,
    HUNTER_S_HATCHET,
    ORCISH_HATCHET,
    SHARP_BONE_AXE,
    TWINBLADE_AXE,

    ELVEN_WAR_AXE,
    DWARVEN_FORGE_HAMMER,
    DARKWOOD_CLEAVER,
    FLAMEFORGED_BATTLE_AXE,
    FROSTBOUND_AXE,

    DRAGON_S_MAW,
    INFERNO_S_EDGE,
    THUNDERSTRIKE_AXE,
    AXE_OF_THE_FALLEN,
    STORMCALLER,

    GODSLAYER,
    CELESTIAL_REAVER,
    ETERNAL_FLAME_AXE,
    AXE_OF_THE_ANCIENTS,
    FROSTMOURNE,

    AXE_OF_RAGNAROK,
    WORLDBREAKER,
    ECLIPSE_AXE,
    SOUL_CLEAVER,
    THE_ENDBRINGER,

    NUM_AXES
};